### ISSUE TITLE
How do you run it?

### ISSUE THREAD

**Issue by rashiq** [mhils/mitmdemo#1]
Hi!
I was at the hackathon you guys created this at (jacobshack).
I recently rediscovered this repo (good thing I starred it) and wanted to know how to run this.
So I set up the local flask server, what now? In your demo at jacobshack someone connected to an open wifi network of a mobile device, if I remember correctly. Now how do I put this all together. 

Thanks!

**Comment by mhils** [comment]
Hi Rashiq,
1. Install mitmproxy
2. `mitmdump -s mitm.py`
3. Open http://localhost:8095/
4. Sent traffic through proxy (localhost:8080)

Clear enough? :wink: 

Cheers,
Max
